### ISSUE TITLE
Refactor interop-switch-js to support new cross-network design

### ISSUE THREAD

**Issue by matdehaast** [mojaloop/cross-network#10]
## **Goal**:
As a Mojaloop developer I want to use the updated cross-network proposal for handling interop requests.

**Tasks**:
- [ ] Update mock ALS call (/parties/:type/:type_id) to return new proposed object 
- [ ] Update quotes endpoint
    - [ ] POST endpoint
    - [ ]  PUT endpoint

**Acceptance Criteria**:
- [ ] Can make a API request to interopswitch to handle MOCK ALS call
- [ ] Can make a API request to interopswitch for quote post and put endpoint
- [ ] Designs are up-to date

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
Closing as this hasn't been touched in a few years; please re-open when this becomes active again and if needed
