### ISSUE TITLE
Create postman collection for cross-currency example

### ISSUE THREAD

**Issue by matdehaast** [mojaloop/cross-network#12]
## **Goal**:
As a developer I want to have a postman collection so that I can explore using the cross-currency code

**Tasks**:
- [x] Setup Scripts
    - [x] Routing Setup Script
    - [x] Hub Setup Script
    - [x] FXP Setup Script
- [x] Usage Scripts
 - [x] Initiate a quote request
 - [x] Initiate a transfer request

**Acceptance Criteria**:
- [x] Can setup cross-currency example using postman collection, including routing, FXP and Hub
- [x] Can initiate a quote request
- [x] Can initiate a transfer request

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
