### ISSUE TITLE
Mojaloop HTTP Endpoint

### ISSUE THREAD

**Issue by DonChangfoot** [mojaloop/cross-network#2]
## **Goal**:
As a CNP I want to host a Mojaloop HTTP Endpoint so that I can accept/send mojaloop packets.

**Tasks**:
- [ ] Create a sub-directory for Mojaloop App
- [ ] Define API endpoint for quotes
- [ ] Define API endpoint for transfers
- [ ] Define API endpoint for errors

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @DonChangfoot 
- QA/Review: @adrianhopebailie @matdehaast
