### ISSUE TITLE
FX Rule for CNPs

### ISSUE THREAD

**Issue by DonChangfoot** [mojaloop/cross-network#5]
## **Goal**:
As a CNP I want to be able to provide foreign exchange so that users can perform cross-currency transactions.

**Tasks**:
- [ ] Write a rule to perform foreign exchange
- [ ] Add rule into business rule pipeline

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- #2 

## **Accountability**:
- Owner: @DonChangfoot 
- QA/Review: @adrianhopebailie @matdehaast
