### ISSUE TITLE
Change Request for Moja API to support cross-network

### ISSUE THREAD

**Issue by adrianhopebailie** [mojaloop/cross-network#6]
## **Goal**:
As an implementor I want to get an updated Moja API spec so that my implementation supports cross-network transfers

### Background
There a number of changes that have been proposed to the Open FSP API (Moja API) as a result of the cross-network POC. These are documented [here](https://github.com/mojaloop/cross-network/blob/master/api-changes.md) but need to be submitted to the CCB.

**Tasks**:
- [ ] Complete CCB-defined documentation for proposed changes
- [ ] Submit to CCB

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
