### ISSUE TITLE
Refactor ml-api-adapter to support new Cross-network architecture

### ISSUE THREAD

**Issue by matdehaast** [mojaloop/cross-network#7]
## **Goal**:
As a Mojaloop developer I want to use the new updated cross-network architecture for routing requests.

**Tasks**:
- [x] Merge cross-network branch with master and bring up to date
- [x] Refactor to use proposed design
- [x] Refactor to use new routing service
- [x] Add unit test for using fspiop-account header
- [ ] Add integration test for using fspiop-account header

**Acceptance Criteria**:
- [x] Designs are up-to date
- [x] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- #2 
- #6 
- #3 

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
