### ISSUE TITLE
Refactor central-ledger to support new cross-network architecture

### ISSUE THREAD

**Issue by matdehaast** [mojaloop/cross-network#8]
## **Goal**:
As a Mojaloop developer I want to use the new updated cross-network architecture for routing requests.

**Tasks**:
- [ ] Merge cross-network branch with master and bring up to date
- [ ] Refactor to use proposed design
- [ ] Refactor to use new routing service

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- #2 
- #6 
- #3 
- #7 

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
