### ISSUE TITLE
Mojaloop HTTP Endpoint Manager

### ISSUE THREAD

**Issue by DonChangfoot** [mojaloop/cross-network#9]
## **Goal**:
As a CNP I want to host a Mojaloop Http endpoint manager so that I can receive incoming quote transfer requests from multiple participants.

**Tasks**:
- [ ] Define API endpoint for incoming quotes
- [ ] Define API endpoint for incoming transfers
- [ ] Define the above API per participant i.e. /{participantId}/transfers...
- [ ] Deliver incoming message to the appropriate participant endpoint

**Acceptance Criteria**:
- [ ] Can receive transfer post request from multiple participants
- [ ] Can receive transfer put request from multiple participants
- [ ] Can receive transfer get request from multiple participants
- [ ] Can receive transfer error put request from multiple participants
- [ ] Can receive quote post request from multiple participants
- [ ] Can receive quote put request from multiple participants
- [ ] Can receive quote get request from multiple participants
- [ ] Can receive quote error put request from multiple participants
- [ ] Find the appropriate participant endpoint according to an identifier in the url
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @DonChangfoot 
- QA/Review: @adrianhopebailie @matdehaast

**Comment by elnyry** [comment]
hi @DonChangfoot this looks a bit ambiguous to me, can we discuss this a little bit to get an understanding of what you're planning to do regarding this?
